import type { Musica } from '../types/musica';

export const mockMusicas: Musica[] = [
  {
    id: '1',
    slug: 'como-sao-belos',
    title: 'Como São Belos',
    artist: 'Pe. Zezinho, SCJ',
    cantorId: null,
    cantorSlug: null,
    originalTone: 'G',
    difficulty: 2,
    capo: 0,
    youtubeUrl: 'https://www.youtube.com/watch?v=EXEMPLO1',
    lyrics: null,
    viewsCount: 1420,
    tempoLiturgico: ['TempoComum'],
    ciclo: ['A', 'B', 'C'],
    momento: ['Entrada', 'Envio'],
    chordsContent: '[G]Como são belos sobre os montes...',
  },
  {
    id: '2',
    slug: 'senhor-tende-piedade',
    title: 'Senhor, Tende Piedade',
    artist: 'Comunidade Canção Nova',
    cantorId: null,
    cantorSlug: null,
    originalTone: 'D',
    difficulty: 1,
    capo: 0,
    youtubeUrl: null,
    lyrics: null,
    viewsCount: 980,
    tempoLiturgico: ['TempoComum', 'Quaresma'],
    ciclo: ['A', 'B', 'C'],
    momento: ['AtoPenitencial'],
    chordsContent: '[D]Senhor, tende piedade de nós...',
  },
  {
    id: '3',
    slug: 'gloria-a-deus-nas-alturas',
    title: 'Glória a Deus nas Alturas',
    artist: 'Ziza Fernandes',
    cantorId: null,
    cantorSlug: null,
    originalTone: 'C',
    difficulty: 3,
    capo: 0,
    youtubeUrl: null,
    lyrics: null,
    viewsCount: 2210,
    tempoLiturgico: ['TempoComum', 'Natal', 'Pascoa'],
    ciclo: ['A', 'B', 'C'],
    momento: ['Gloria'],
    chordsContent: '[C]Glória a Deus nas alturas...',
  },
  {
    id: '4',
    slug: 'aleluia-pascal',
    title: 'Aleluia Pascal',
    artist: 'Pe. Fábio de Melo',
    cantorId: null,
    cantorSlug: null,
    originalTone: 'A',
    difficulty: 2,
    capo: 0,
    youtubeUrl: null,
    lyrics: null,
    viewsCount: 3050,
    tempoLiturgico: ['Pascoa'],
    ciclo: ['A', 'B', 'C'],
    momento: ['AclamacaoEvangelho'],
    chordsContent: '[A]Aleluia, aleluia, aleluia...',
  },
  {
    id: '5',
    slug: 'ofertorio-do-pao-e-vinho',
    title: 'Recebe, ó Pai, Este Pão e Vinho',
    artist: 'Pe. Zezinho, SCJ',
    cantorId: null,
    cantorSlug: null,
    originalTone: 'E',
    difficulty: 2,
    capo: 0,
    youtubeUrl: null,
    lyrics: null,
    viewsCount: 1670,
    tempoLiturgico: ['TempoComum'],
    ciclo: ['A', 'B', 'C'],
    momento: ['Ofertorio'],
    chordsContent: '[E]Recebe, ó Pai, este pão e vinho...',
  },
  {
    id: '6',
    slug: 'santo-santo-santo',
    title: 'Santo, Santo, Santo é o Senhor',
    artist: 'Comunidade Toca de Adulão',
    cantorId: null,
    cantorSlug: null,
    originalTone: 'F',
    difficulty: 1,
    capo: 0,
    youtubeUrl: null,
    lyrics: null,
    viewsCount: 4120,
    tempoLiturgico: ['TempoComum', 'Advento', 'Quaresma', 'Natal', 'Pascoa'],
    ciclo: ['A', 'B', 'C'],
    momento: ['Santo'],
    chordsContent: '[F]Santo, santo, santo é o Senhor...',
  },
  {
    id: '7',
    slug: 'cordeiro-de-deus',
    title: 'Cordeiro de Deus',
    artist: 'Ziza Fernandes',
    cantorId: null,
    cantorSlug: null,
    originalTone: 'Am',
    difficulty: 2,
    capo: 0,
    youtubeUrl: null,
    lyrics: null,
    viewsCount: 1890,
    tempoLiturgico: ['TempoComum', 'Quaresma'],
    ciclo: ['A', 'B', 'C'],
    momento: ['Cordeiro'],
    chordsContent: '[Am]Cordeiro de Deus, que tirais...',
  },
  {
    id: '8',
    slug: 'vem-espirito-de-deus',
    title: 'Vem, Espírito de Deus',
    artist: 'Frei Gilson',
    cantorId: null,
    cantorSlug: null,
    originalTone: 'D',
    difficulty: 2,
    capo: 0,
    youtubeUrl: null,
    lyrics: null,
    viewsCount: 2540,
    tempoLiturgico: ['Pascoa'],
    ciclo: ['A', 'B', 'C'],
    momento: ['Comunhao'],
    chordsContent: '[D]Vem, Espírito de Deus, vem...',
  },
  {
    id: '9',
    slug: 'ide-em-paz',
    title: 'Ide em Paz',
    artist: 'Pe. Zezinho, SCJ',
    cantorId: null,
    cantorSlug: null,
    originalTone: 'G',
    difficulty: 1,
    capo: 0,
    youtubeUrl: null,
    lyrics: null,
    viewsCount: 1120,
    tempoLiturgico: ['TempoComum'],
    ciclo: ['A', 'B', 'C'],
    momento: ['Envio'],
    chordsContent: '[G]Ide em paz e o Senhor vos acompanhe...',
  },
  {
    id: '10',
    slug: 'povo-de-deus',
    title: 'Povo de Deus',
    artist: 'Pe. Zezinho, SCJ',
    cantorId: null,
    cantorSlug: null,
    originalTone: 'G',
    difficulty: 2,
    capo: 0,
    youtubeUrl: null,
    lyrics: null,
    viewsCount: 5680,
    tempoLiturgico: ['TempoComum'],
    ciclo: ['A', 'B', 'C'],
    momento: ['Entrada'],
    chordsContent: '[G]Povo de Deus, povo da vida...',
  },
];
